export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FILTER_PRODUCTS_BY_CAT = 'FILTER_PRODUCTS_BY_CAT'
export const GET_USER = 'GET_USER'

export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const INCREMENT_CART_ITEM = 'INCREMENT_CART_ITEM'
export const DECREMENT_CART_ITEM = 'DECREMENT_CART_ITEM'
